version: '3.4'

networks:
  net:
    driver: bridge


services:
  postgresql:
    container_name: postgresql
    image: postgres:15.2
    volumes:
      - postgres-data-teboil:/var/lib/postgresql/data
      - database_backup:/var/backup_db
    restart: always
    env_file: .env
    privileged: true
    ports:
      - "5776:5432"
    networks:
      net:


  qr-service:
    container_name: qr-service
    env_file: .env
    image: ${TEST_STAGE_IMAGE_APP_TAG}
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - postgresql
    networks:
      net:
  
volumes:
  database_backup:
  postgres-data-teboil:
